### ISSUE TITLE
ans in Workspace

### ISSUE THREAD

**Issue by peteraberg** [suever/nuke#1]
when i run nuke i end up with ans in the workspace. the ans comes from the fclose('all'); call. you might want to close the files before clearing the workspace.

thanks for sharing!

**Comment by suever** [comment]
Thanks for pointing this out. That is very strange behavior but it should now be fixed.

**Comment by peteraberg** [comment]
Thanks for the fix!

I agree that the fclose('all') is very odd. Do you have any idea why it leaves an ans in the workspace? I am very surprised.

**Comment by suever** [comment]
I feel like that has to be a bug. It should not leave anything in the workspace if terminated with a semicolon. At least that's what I would expect.

**Comment by suever** [comment]
After playing around it appears that even with semi-colon termination, all un-assigned outputs from any statement are stored in ANS (which makes sense I guess). I guess I didn't realize that because you typically only see ANS when you forget to terminate with a semicolon. So it's always there as long as you have outputs from a function you just may not always see it. Thanks again.
